[package]
authors = ["tharun"]
edition = "2018"
name = "uptime-checker"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lettre = "0.9.0"
lettre_email="0.9.0"
req